@startuml repeatTimed
[->"Agent": top:repeatTimed()
activate "Agent"

loop every 500ms
    group strict
        par
            "Agent" -> "VirtualCoffeeMachine" : readProperty: "state"
            activate "VirtualCoffeeMachine"
            "VirtualCoffeeMachine" --> "Agent" : response
            deactivate "VirtualCoffeeMachine"
        end 
        par 
            "Agent" -> "TestThing" : writeProperty: "string"
        end 
    end
end

[<-"Agent"
deactivate "Agent"
@enduml